package src

const INT = "Int"
const STR = "Str"
const CALL = "Call"
const BINARY = "Binary"
const FUNCTION = "Function"
const LET = "Let"
const IF = "If"
const PRINT = "Print"
const FIRST = "First"
const SECOND = "Second"
const BOOL = "Bool"
const TUPLE = "Tuple"
const VAR = "Var"

// Binary operators
const ADD = "Add"
const SUB = "Sub"
const MUL = "Mul"
const DIV = "Div"
const REM = "Rem"
const EQ = "Eq"
const NEQ = "Neq"
const LT = "Lt"
const GT = "Gt"
const LTE = "Lte"
const GTE = "Gte"
const AND = "And"
const OR = "Or"
